-- zde ulozte par SELECT dotazu vyuzivajicich JOIN, prip. UNION nad tabulkami v projektu
-- 
-- priklad 1 - adresy vsech / new_views
-- SELECT *
-- FROM address_list;
-- 
-- priklad 2 seznam studentu / new_views
-- SELECT *
-- FROM student_list;
-- 
-- priklad 3 vypis ucitelu / new_views
-- SELECT *
-- FROM trainer_list;