-- smazani tablu
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS trainer CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS topic CASCADE;
DROP TABLE IF EXISTS trainer_course_assigments CASCADE;
DROP TABLE IF EXISTS student_signup CASCADE;